name: Sync to Publish Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Confirm token is populated
        run: |
          if [ -z "${{ secrets.PUBLISH_TOKEN }}" ]; then
            echo "❌ PUBLISH_TOKEN is not set or empty"
            exit 1
          else
            echo "✅ PUBLISH_TOKEN is set"
          fi

      - name: Prepare cleaned branch
        run: |
          export BRANCH_NAME="${GITHUB_REF_NAME}"
          echo "Current branch: $BRANCH_NAME"

          # Create a working copy with .github removed
          git checkout -b temp-publish
          git rm -r --cached .github || echo "No .github directory to remove"
          git commit -m "Remove GitHub workflows before publishing" || echo "Nothing to commit"

      - name: Push cleaned branch to publish repo
        env:
          TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: |
          git remote add publish \
            https://x-access-token:${TOKEN}@github.com/Mirantis/k0rdent-enterprise-docs-publish.git

          # Push temp-publish to the same name as the source branch
          git push publish HEAD:"${GITHUB_REF_NAME}" --force

      - name: Cleanup
        run: |
          git checkout "${GITHUB_REF_NAME}"
          git branch -D temp-publish
