name: Sync to Publish Repo

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          ref: release-v1.0.0
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Force push to publish repo using PAT
        run: |
          git push https://x-access-token:${{ secrets.PUBLISH_TOKEN }}@github.com/Mirantis/k0rdent-enterprise-docs-publish.git release-v1.0.0 --force
